#!/bin/bash
#
# This script gets the reading from the cpu temperature sensor for
# monitoring system performance.
#
paste <(cat /sys/class/thermal/thermal_zone*/type) <(cat /sys/class/thermal/thermal_zone*/temp) | column -s $'\t' -t | sed 's/\(.\)..$/.\1°C/'

